routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


Auth::routes();

Route::post('broadcasting/auth', 'Auth\BroadcastController@authorization');

Route::get('/', 'HomeController@index')->name('home');

Route::post('/createOrder', 'OrderController@createOrder');
Route::post('/deleteOrder', 'OrderController@deleteOrder');
Route::get('/paymentProcess', 'InvoiceController@pending');
Route::get('/paymentSuccess', 'InvoiceController@success');
Route::post('/paymentSuccess', 'InvoiceController@getter');
Route::get('/paymentErr', 'InvoiceController@err');
//Route::get('/orders', 'OrderController@getOrdersByDate');
Route::post('/orders', 'OrderController@getOrdersByMonth');
Route::get('/adminordersbydate', 'OrderController@getAdminOrdersByDate');
Route::get('/about', 'HomeController@about');


Route::get('setting', 'SettingController@index')->name('setting.index');
Route::get('instruments', 'InstrumentController@index')->name('instrument.index');



Route::get('/home', 'HomeController@index');

Route::post('check_datetime', 'OrderController@checkDatetime');

Route::resource('session', 'SessionController');

Route::group([ 'prefix' => 'admin', 'middleware' => 'auth' ], function (){
    Route::get('/', 'AdminController@admin')->middleware('is_admin')->name('admin.index');
    Route::get('/update_orders', 'AdminController@orders')->middleware('is_admin');


    Route::group([ 'prefix' => 'order' ], function (){
        Route::get('/', 'OrderController@index')->name('orders.index');
        Route::get('/{id}', 'OrderController@show')->name('orders.show');
        Route::get('/edit/{id}', 'OrderController@edit')->name('orders.edit');
        Route::put('/update', 'OrderController@update')->name('orders.update');
        Route::get('/delete/{id}', 'OrderController@delete')->name('orders.delete');


    });
    Route::group([ 'prefix' => 'payment' ], function (){
        Route::put('/update', 'InvoiceController@update');
    });



    Route::group(['namespace' => 'Admin'], function (){

        Route::resource('order-time', 'OrderTimeController')->parameters([
            'order-time' => 'id'
        ]);

        Route::resource('order-instrument', 'OrderInstrumentController')->parameters([
            'order-instrument.destroy' => 'id, order_id'
        ]);

        Route::resource('schedules', 'SchedulesController')->parameters([
            'schedules.destroy' => 'id, order_id'
        ]);
    });

    Route::group(['namespace' => 'Admin'], function (){

        /**
         * Main Setting
         */
        Route::get('setting/delete/{id}', 'SettingController@delete')->name('setting.delete');
        Route::resource('setting', 'SettingController');

        /**
         * Category
         */
        Route::resource('category', 'CategoryController');

        /**
         * Hour
         */
        Route::resource('hour', 'HourController');
        Route::get('/hour/{day}/duplicate/{category_id}', 'HourController@duplicate')->name('hour.duplicate');
        Route::post('/hour/copy/{category_id}', 'HourController@copy')->name('hour.copy');

        /**
         * Discount
         */
        Route::resource('discount', 'DiscountController');

        /**
         * Reservation
         */
        Route::resource('reservation', 'ReservationController');

        /**
         * Instrument
         */
        Route::get('instrument/delete/{id}', 'InstrumentController@delete')->name('instrument.delete');
        Route::resource('instrument', 'InstrumentController');

        /**
         * Security
         */
        Route::resource('security', 'SecurityController');

    });


});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{

    protected $table = 'categories';

    protected $fillable = [
        'parent_id',
        'name',
        'sub_name',
        'min_hour'
    ];

    public function parent()
    {
        return $this->hasOne(Category::class, 'id', 'parent_id');
    }

    public function children()
    {
        return $this->hasMany(Category::class, 'parent_id', 'id');
    }

    public function hours()
    {
        return $this->hasMany(Hour::class, 'category_id', 'id');
    }

    public function days()
    {
        return Hour::byDaysWithHour($this->id);
    }

    public function discounts()
    {
        return $this->hasMany(Discount::class, 'category_id', 'id');
    }

    public function reservations()
    {
        return $this->hasMany(Reservation::class, 'category_id', 'id');
    }

}

app/Http/Controllers/API/v1/CategoryController.php
<?php

namespace App\Http\Controllers\API\v1;

use App\Category;
use App\Hour;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories  = collect(Category::with(['children', 'discounts', 'reservations'])->get());

        $categories->map(function ($category) {
            return $category->days = Hour::byDaysWithHour($category->id);
        });

        return response(
            [
                'message' => 'Список всех категорий',
                'data' => $categories
            ],
            200,
            [
                'Content-Type' => 'application/json'
            ]
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
//        return response('', 201);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return response('', 201);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Hour;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

class CategoryController extends Controller
{

    private $model;

    public function __construct()
    {
        $this->model = new Category();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.category.index', [
           'categories' => $this->model->with(['parent'])->get()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create', [
            'categories' => $this->model->get()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            'name' => [
                'required',
                'unique:'.$this->model->getTable().',name',
            ],
            'sub_name' => [
                'required',
                'unique:'.$this->model->getTable().',sub_name'
            ],
            'min_hour' => 'required|min:1',
        ], [], $request->all());

        $category = $this->model::create($request->all());

        if(isset($category->id)){
            return redirect()->route('category.edit', [
                'id' => $category->id
            ]);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->model::find($id);


        $days = Hour::byDays($id);

        $discounts = $category->discounts;

        $reservations = $category->reservations;

        return view('admin.category.edit', [
            'id' => $id,
            'category' => $category,
            'categories' => $this->model->where('id','!=', $id)->get(),
            'days' => $days,
            'discounts' => $discounts,
            'reservations' => $reservations
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => [
                'required',
                Rule::unique($this->model->getTable())->ignore($id)
            ],
            'sub_name' => [
                'required',
                Rule::unique($this->model->getTable())->ignore($id)
            ],
            'min_hour' => 'required|min:1',
        ], [], $request->all());

        $category = $this->model::find($id);

        if(!isset($category->id)){
            return redirect()->back();
        }

        $category->name = $request->name;
        $category->sub_name = $request->sub_name;
        $category->min_hour = $request->min_hour;

        if(isset($request->parent_id) && $request->parent_id){
            $category->parent_id = $request->parent_id;
        }

        $category->save();

        if(isset($category->id)){
            return redirect()->route('category.edit', [
                'id' => $id,
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->model::destroy($id);
        return redirect()->back();
    }
}

resources/views/admin/category/create.blade.php
@extends('adminl_ayout_without_vue')

@section('title')
    Admin.STUDIO
@endsection

@section('content')


    <section class="main">

        <div class="container">

            <div class="col-sm-12 mt-3">

                <div class="row">

                    <div class="col-sm-6">

                        <a href="{{ route('category.index') }}" class="btn main-bg btn-block">Вернутся к категориям</a>

                    </div>

                </div>

            </div>

            <div class="col-sm-12">

                <form action="{{ route('category.store') }}" class="mt-3" method="post">
                    @csrf
                    @method('POST')

                    <div class="row">

                        <div class="col-sm-12 form-group">

                            <label for="name" class="text-white">Название категории</label>
                            <input name="name" id="name" type="text" class="form-control" value="{{ old('name') }}" required>
                            @if($errors->has('name'))<div class="help-block text-danger">{{ $errors->get('name')[0] }}</div> @endif
                        </div>

                        <div class="col-sm-12 form-group">

                            <label for="sub_name" class="text-white">Название категории на английском или транслитом</label>
                            <input name="sub_name" id="sub_name" type="text" class="form-control" value="{{ old('sub_name') }}" required>
                            @if($errors->has('sub_name'))<div class="help-block text-danger">{{ $errors->get('sub_name')[0] }}</div> @endif

                        </div>

                        @if(!empty($categories->count()))
                            <div class="col-sm-12 form-group">
                                <label for="parent" class="text-white">Указать родительскую категорию (необязательно)</label>
                                <select name="parent_id" id="parent" class="form-control">
                                        <option value="0">Выберите Категорию</option>

                                        @foreach($categories as $category)
                                            @if(old('parent_id') == $category->id)
                                                <option value="{{ $category->id }}" selected>{{ $category->name }}</option>
                                            @else
                                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                                            @endif
                                        @endforeach
                                </select>
                                @if($errors->has('parent_id'))<div class="help-block text-danger">{{ $errors->get('parent_id')[0] }}</div> @endif

                            </div>
                        @endif

                        <div class="col-sm-12 form-group">

                            <label for="min_hour" class="text-white">Минимальное кол-во часов</label>
                            <input name="min_hour" id="min_hour" type="text" class="form-control" value="{{ old('min_hour') }}" required>
                            @if($errors->has('min_hour'))<div class="help-block text-danger">{{ $errors->get('min_hour')[0] }}</div> @endif

                        </div>

                        <div class="col-sm-12">
                            <button type="submit" class="btn btn-block btn-success">Создать категорию</button>
                        </div>


                    </div>

                </form>

            </div>

        </div>
    </section>

@endsection

resources/views/admin/category/edit.blade.php
@extends('adminl_ayout_without_vue')

@section('title')
    Admin.STUDIO
@endsection

@section('content')


    <section class="main">

        <div class="container">

            <div class="row">

                <div class="col-sm-12 mt-3">

                    <div class="row">

                        <div class="col-sm-6">

                            <a href="{{ route('category.index') }}" class="btn main-bg btn-block">Вернутся к категориям</a>

                        </div>

                    </div>

                </div>

                <div class="col-sm-12">

                    <form action="{{ route('category.update', ['id' => $id]) }}" class="mt-3" method="post">
                        @csrf
                        @method('PUT')

                        <div class="row">

                            <div class="col-sm-12 form-group">

                                <label for="name" class="text-white">Название категории</label>
                                <input name="name" id="name" type="text" class="form-control" value="{{ $category->name }}" required>
                                @if($errors->has('name'))<div class="help-block text-danger">{{ $errors->get('name')[0] }}</div> @endif
                            </div>

                            <div class="col-sm-12 form-group">

                                <label for="sub_name" class="text-white">Название категории на английском или транслитом</label>
                                <input name="sub_name" id="sub_name" type="text" class="form-control" value="{{ $category->sub_name }}" required>
                                @if($errors->has('sub_name'))<div class="help-block text-danger">{{ $errors->get('sub_name')[0] }}</div> @endif

                            </div>

                            @if(!empty($categories->count()))
                                <div class="col-sm-12 form-group">
                                    <label for="parent" class="text-white">Указать родительскую категорию (необязательно)</label>
                                    <select name="parent_id" id="parent" class="form-control">
                                        <option value="0">Выберите Категорию</option>

                                        @foreach($categories as $_category)
                                                <option class="selected" value="{{ $_category->id }}" @if($category->parent_id == $_category->id) selected="selected"  @endif >{{ $_category->name }}</option>
                                        @endforeach
                                    </select>
                                    @if($errors->has('parent_id'))<div class="help-block text-danger">{{ $errors->get('parent_id')[0] }}</div> @endif

                                </div>
                            @endif

                            <div class="col-sm-12 form-group">

                                <label for="min_hour" class="text-white">Минимальное кол-во часов</label>
                                <input name="min_hour" id="min_hour" type="text" class="form-control" value="{{ $category->min_hour }}" required>
                                @if($errors->has('min_hour'))<div class="help-block text-danger">{{ $errors->get('min_hour')[0] }}</div> @endif

                            </div>

                            <div class="col-sm-12">
                                <button type="submit" class="btn btn-block btn-success">Обновить категорию</button>
                            </div>

                        </div>

                    </form>

                </div>

                <div class="col-sm-12 mt-5">

                    <div class="row">

                        <div class="col-sm-4">
                            @include('admin.category.list_hour')
                        </div>
                        <div class="col-sm-4">
                            @include('admin.category.list_discount')
                        </div>
                        <div class="col-sm-4">
                            @include('admin.category.list_reservation')
                        </div>

                    </div>

                </div>

            </div>



        </div>
    </section>

@endsection

resources/views/admin/category/index.blade.php
@extends('adminl_ayout_without_vue')

@section('title')
    Admin.STUDIO
@endsection

@section('content')


    <section class="main">

        <div class="container">

            <div class="row mt-3">
                <div class="col-sm-12 form-group d-flex align-content-center flex-column justify-content-end">
                    <a class="btn btn-success" href="{{ route('category.create') }}">Добавить Категорию</a>
                </div>
            </div>

            <div class="row">

                <table class="table text-white">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Название</th>
                        <th scope="col">Под название</th>
                        <th scope="col">Мин часов</th>
                        <th scope="col">Родитель</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @if(!empty($categories))
                        @foreach($categories as $category)
                            <tr>
                                <td>ID</td>
                                <td>{{ $category->name }}</td>
                                <td>{{ $category->sub_name }}</td>
                                <td>{{ $category->min_hour }}</td>
                                <td>{{ isset($category->parent->name)? $category->parent->name: 0 }}</td>
                                <td>
                                    <div class="row">
                                        <a class="btn btn-warning mr-2" href="{{ route('category.edit', ['id' => $category->id]) }}"><i class="fas fa-wrench"></i></a>
                                        <form action="{{ route('category.destroy', ['id' => $category->id]) }}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-danger" type="submit"><i class="fas fa-window-close"></i></button>

                                        </form>
                                    </div>
{{--                                    <a class="btn btn-danger" href="{{ route('category.destroy', ['id' => $category->id]) }}"><i class="fas fa-window-close"></i></a>--}}
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td>ID</td>
                            <td>Таблица</td>
                            <td>Пустая</td>
                            <td></td>
                            <td></td>
                            <td>
                                <a class="btn btn-warning" href="#"><i class="fas fa-wrench"></i></a>
                                <a class="btn btn-danger" href="#"><i class="fas fa-window-close"></i></a>
                            </td>
                        </tr>
                    @endif
                    </tbody>
                </table>

            </div>

        </div>
    </section>

@endsection

resources/views/admin/category/list_discount.blade.php
@if($discounts->count())
    <h3 class="text-center text-white">Скидки</h3>
    <table class="table text-white">
        <thead>
        <tr>
            <th scope="col">Название</th>
            <th scope="col">Значение</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach($discounts as $discount)

            <tr>
                <td>{{ $discount->name }}</td>
                <td>{{ $discount->getValue() }}</td>
                <td>
                    <div class="row">
                        <a class="btn btn-warning mr-2" href="{{ route('discount.edit', ['id' => $discount->id, 'category_id' => $id]) }}"><i class="fas fa-wrench"></i></a>
                        <form action="{{ route('discount.destroy', ['id' => $discount->id]) }}" method="post">
                            @csrf
                            @method('DELETE')
                            <input type="hidden" name="category_id" value="{{ $id }}">
                            <button class="btn btn-danger" type="submit"><i class="fas fa-window-close"></i></button>

                        </form>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>


@endif
<div class="form-group mt-4">
    <a href="{{ route('discount.create', ['category_id' => $id]) }}" class="btn btn-block btn-success">Добавить скидку</a>
</div>

resources/views/admin/category/list_hour.blade.php
@if($days->count())
    <h3 class="text-center text-white">Рассписание</h3>
    <table class="table text-white">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">День</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach($days as $day)

            <tr>
                <td>{{ $day->day }}</td>
                <td>{{ $day->getName() }}</td>
                <td>
                    <div class="row">
                        <a class="btn btn-warning mr-2" href="{{ route('hour.edit', ['id' => $day->day, 'category_id' => $id]) }}"><i class="fas fa-wrench"></i></a>
                        <a class="btn btn-info mr-2" href="{{ route('hour.duplicate', ['day' => $day->day, 'category_id' => $id]) }}"><i class="fas fa-copy"></i></a>
                        <form action="{{ route('hour.destroy', ['id' => $day->day]) }}" method="post">
                            @csrf
                            @method('DELETE')
                            <input type="hidden" name="category_id" value="{{ $id }}">
                            <button class="btn btn-danger" type="submit"><i class="fas fa-window-close"></i></button>

                        </form>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>


@endif
@if(!isset($day) || isset($day) && $days->count() < count($day->getDays()))
    <div class="form-group mt-4">
        <a href="{{ route('hour.create', ['category_id' => $id]) }}" class="btn btn-block btn-success">Добавить время</a>
    </div>
@endif

resources/views/admin/category/list_reservation.blade.php
@if($reservations->count())
    <h3 class="text-center text-white">Абонименты</h3>
    <table class="table text-white">
        <thead>
        <tr>
            <th scope="col">название</th>
            <th scope="col">значение</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach($reservations as $reservation)

            <tr>
                <td>{{ $reservation->name }}</td>
                <td>{{ $reservation->getValue() }}</td>
                <td>
                    <div class="row">
                        <a class="btn btn-warning mr-2" href="{{ route('reservation.edit', ['id' => $reservation->id, 'category_id' => $category->id]) }}"><i class="fas fa-wrench"></i></a>
                        <form action="{{ route('reservation.destroy', ['id' => $reservation->id]) }}" method="post">
                            @csrf
                            @method('DELETE')
                            <input type="hidden" name="category_id" value="{{ $id }}">
                            <button class="btn btn-danger" type="submit"><i class="fas fa-window-close"></i></button>

                        </form>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>


@endif
<div class="form-group mt-4">
    <a href="{{ route('reservation.create', ['category_id' => $id]) }}" class="btn btn-block btn-success">Добавить абонимент</a>
</div>