routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


Auth::routes();

Route::post('broadcasting/auth', 'Auth\BroadcastController@authorization');

Route::get('/', 'HomeController@index')->name('home');

Route::post('/createOrder', 'OrderController@createOrder');
Route::post('/deleteOrder', 'OrderController@deleteOrder');
Route::get('/paymentProcess', 'InvoiceController@pending');
Route::get('/paymentSuccess', 'InvoiceController@success');
Route::post('/paymentSuccess', 'InvoiceController@getter');
Route::get('/paymentErr', 'InvoiceController@err');
//Route::get('/orders', 'OrderController@getOrdersByDate');
Route::post('/orders', 'OrderController@getOrdersByMonth');
Route::get('/adminordersbydate', 'OrderController@getAdminOrdersByDate');
Route::get('/about', 'HomeController@about');


Route::get('setting', 'SettingController@index')->name('setting.index');
Route::get('instruments', 'InstrumentController@index')->name('instrument.index');



Route::get('/home', 'HomeController@index');

Route::post('check_datetime', 'OrderController@checkDatetime');

Route::resource('session', 'SessionController');

Route::group([ 'prefix' => 'admin', 'middleware' => 'auth' ], function (){
    Route::get('/', 'AdminController@admin')->middleware('is_admin')->name('admin.index');
    Route::get('/update_orders', 'AdminController@orders')->middleware('is_admin');


    Route::group([ 'prefix' => 'order' ], function (){
        Route::get('/', 'OrderController@index')->name('orders.index');
        Route::get('/{id}', 'OrderController@show')->name('orders.show');
        Route::get('/edit/{id}', 'OrderController@edit')->name('orders.edit');
        Route::put('/update', 'OrderController@update')->name('orders.update');
        Route::get('/delete/{id}', 'OrderController@delete')->name('orders.delete');


    });
    Route::group([ 'prefix' => 'payment' ], function (){
        Route::put('/update', 'InvoiceController@update');
    });



    Route::group(['namespace' => 'Admin'], function (){

        Route::resource('order-time', 'OrderTimeController')->parameters([
            'order-time' => 'id'
        ]);

        Route::resource('order-instrument', 'OrderInstrumentController')->parameters([
            'order-instrument.destroy' => 'id, order_id'
        ]);

        Route::resource('schedules', 'SchedulesController')->parameters([
            'schedules.destroy' => 'id, order_id'
        ]);
    });

    Route::group(['namespace' => 'Admin'], function (){

        /**
         * Main Setting
         */
        Route::get('setting/delete/{id}', 'SettingController@delete')->name('setting.delete');
        Route::resource('setting', 'SettingController');

        /**
         * Category
         */
        Route::resource('category', 'CategoryController');

        /**
         * Hour
         */
        Route::resource('hour', 'HourController');
        Route::get('/hour/{day}/duplicate/{category_id}', 'HourController@duplicate')->name('hour.duplicate');
        Route::post('/hour/copy/{category_id}', 'HourController@copy')->name('hour.copy');

        /**
         * Discount
         */
        Route::resource('discount', 'DiscountController');

        /**
         * Reservation
         */
        Route::resource('reservation', 'ReservationController');

        /**
         * Instrument
         */
        Route::get('instrument/delete/{id}', 'InstrumentController@delete')->name('instrument.delete');
        Route::resource('instrument', 'InstrumentController');

        /**
         * Security
         */
        Route::resource('security', 'SecurityController');

    });


});

app/Setting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{

    protected $table = 'settings';

    protected $primaryKey = 'name';

    public $incrementing = false;

}

app/Http/Controllers/Admin/SettingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Setting;
use Illuminate\Http\Request;

class SettingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        return view('admin.setting.index');

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.setting.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'name' => 'required|unique:settings|max:255',
            'value' => 'required',
        ]);

        if(substr($request->name,0,1) == '_'){
            $setting = new Setting();
            $setting->name = 'min_hours_' . $request->value;
            $setting->value = 0;
            $setting->save();

            $setting = new Setting();
            $setting->name = 'sale_' . $request->value;
            $setting->value = 0;
            $setting->save();
        }

        $setting = new Setting();
        $setting->name = $request->name;
        $setting->value = $request->value;
        $setting->save();


        return redirect()->route('setting.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function show(Setting $setting)
    {
        return view('admin.setting.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function edit(Setting $setting)
    {
        $disabled_name = false;
        \session()->put('old', $setting);

        foreach (config('app.disabled_name') as $name){
            if(strpos($setting->name, $name) === false){
                $disabled_name = false;
            }else{
                $disabled_name = true;
                break;
            }
        }

        return view('admin.setting.edit', [
            'setting' => $setting,
            'disabled_name' => $disabled_name
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Setting $setting)
    {
        $request->validate([
            'value' => 'required|max:255',
        ]);

        if(isset($request->name))
            if(substr($request->name,0,1) == '_'){
                $old = session()->get('old');
                Setting::where('name', 'min_hours_' . $old->value)->update(['name' => 'min_hours_' . $request->value]);
                Setting::where('name', 'sale_' . $old->value)->update(['name' => 'sale_' . $request->value]);
            }

        isset($request->name) ? $setting->name = $request->name: false;
        $setting->value = $request->value;
        $setting->save();

        return redirect()->route('setting.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function delete(Setting $setting, Request $request)
    {

        if(substr($request->id,0,1) == '_'){
            $parent = $setting::where('name', $request->id)->first();
            Setting::where('name', 'min_hours_' . $parent->value)->delete();
            Setting::where('name', 'sale_' . $parent->value)->delete();
        }
        $setting::where('name', $request->id)->delete();
        return redirect()->back();
    }

}

app/Http/Controllers/SettingController.php
<?php

namespace App\Http\Controllers;

use App\Setting;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Session\Session;

class SettingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        if($request->type == 'json'){
            return response()->json(Setting::all());
        }else{
            return view('admin.setting.index', [
                'settings' => Setting::all()
            ]);
        }

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.setting.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'name' => 'required|unique:settings|max:255',
            'value' => 'required',
        ]);

        if(substr($request->name,0,1) == '_'){
            $setting = new Setting();
            $setting->name = 'min_hours_' . $request->value;
            $setting->value = 0;
            $setting->save();

            $setting = new Setting();
            $setting->name = 'sale_' . $request->value;
            $setting->value = 0;
            $setting->save();
        }

        $setting = new Setting();
        $setting->name = $request->name;
        $setting->value = $request->value;
        $setting->save();


        return redirect()->route('setting.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function show(Setting $setting)
    {
        return view('admin.setting.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function edit(Setting $setting)
    {
        $disabled_name = false;
        \session()->put('old', $setting);

        foreach (config('app.disabled_name') as $name){
            if(strpos($setting->name, $name) === false){
                $disabled_name = false;
            }else{
                $disabled_name = true;
                break;
            }
        }

        return view('admin.setting.edit', [
            'setting' => $setting,
            'disabled_name' => $disabled_name
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Setting $setting)
    {
        $request->validate([
            'value' => 'required|max:255',
        ]);

        if(isset($request->name))
            if(substr($request->name,0,1) == '_'){
                $old = session()->get('old');
                Setting::where('name', 'min_hours_' . $old->value)->update(['name' => 'min_hours_' . $request->value]);
                Setting::where('name', 'sale_' . $old->value)->update(['name' => 'sale_' . $request->value]);
            }

        isset($request->name) ? $setting->name = $request->name: false;
        $setting->value = $request->value;
        $setting->save();

        return redirect()->route('setting.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function delete(Setting $setting, Request $request)
    {

        if(substr($request->id,0,1) == '_'){
            $parent = $setting::where('name', $request->id)->first();
            Setting::where('name', 'min_hours_' . $parent->value)->delete();
            Setting::where('name', 'sale_' . $parent->value)->delete();
        }
        $setting::where('name', $request->id)->delete();
        return redirect()->back();
    }

}

resources/views/admin/setting/create.blade.php
@extends('adminl_ayout_without_vue')

@section('title')
    Admin.STUDIO
@endsection

@section('content')

    <section class="main">

        <div class="container">

            <div class="row mt-3">
                <div class="col-sm-12 form-group d-flex align-content-center flex-column justify-content-end">
                    <a class="btn btn-success" href="{{ route('setting.index') }}">Вернуться</a>
                </div>
            </div>

            <div class="row">

                <div class="col-12">

                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <form action="{{ route('setting.store') }}" method="POST">
                        @csrf
                        <div class="form-group">
                            <label for="exampleInputEmail1">Name</label>
                            <input type="text" name="name" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter name" required>
                            <small id="emailHelp" class="form-text text-muted">We'll never share your name with anyone else.</small>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Value</label>
                            <input type="text" name="value" class="form-control" id="exampleInputPassword1" placeholder="Value" required>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>

            </div>

        </div>
    </section>

@endsection

resources/views/admin/setting/edit.blade.php
@extends('adminl_ayout_without_vue')

@section('title')
    Admin.STUDIO
@endsection

@section('content')

    <section class="main">

        <div class="container">

            <div class="row mt-3">
                <div class="col-sm-12 form-group d-flex align-content-center flex-column justify-content-end">
                    <a class="btn btn-success" href="{{ route('setting.index') }}">Вернуться</a>
                </div>
            </div>

            <div class="row">

                <div class="col-12">

                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <form action="{{ route('setting.update', ['setting' => $setting->name]) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="exampleInputEmail1">Name</label>
                            <input type="text" name="name" value="{{ $setting->name }}" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter name" @if($disabled_name) disabled @endif required>
                            <small id="emailHelp" class="form-text text-muted">We'll never share your name with anyone else.</small>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Value</label>
                            <input type="text" name="value" value="{{ $setting->value }}" class="form-control" id="exampleInputPassword1" placeholder="Value" required>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>

            </div>

        </div>
    </section>

@endsection

resources/views/admin/setting/index.blade.php
@extends('adminl_ayout_without_vue')

@section('title')
    Admin.STUDIO
@endsection

@section('content')

    <section class="main mt-5">

        <div class="container">

            <div class="row">

                <div class="col">

                    <h1 class="main-color text-center mb-5 ">
                        Панель настроек вашего пориложения
                    </h1>

                </div>

            </div>

            <div class="row">

                <div class="col-sm-4 col-12 mb-5">

                    <div class="setting-item setting-border">

                        <a class="setting-link" href="{{ route('category.index') }}">
                            <p><i class="fas fa-th-list fz-2-em"></i></p>
                            <p>Категории</p>
                        </a>

                    </div>

                </div>

                <div class="col-sm-4 col-12 mb-5">

                    <div class="setting-item setting-border">

                        <a class="setting-link" href="{{ route('instrument.index') }}">
                            <p><i class="fas fa-guitar fz-2-em"></i></p>
                            <p class="fz-1-em">Музыкальные инструменты</p>
                        </a>

                    </div>

                </div>

                <div class="col-sm-4 col-12 mb-5">

                    <div class="setting-item setting-border">

                        <a class="setting-link" href="{{ route('security.index') }}">
                            <p><i class="fas fa-shield-alt fz-2-em"></i></p>
                            <p class="fz-1-em">Безопасность</p>
                        </a>

                    </div>

                </div>


            </div>

        </div>
    </section>

@endsection