routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


Auth::routes();

Route::post('broadcasting/auth', 'Auth\BroadcastController@authorization');

Route::get('/', 'HomeController@index')->name('home');

Route::post('/createOrder', 'OrderController@createOrder');
Route::post('/deleteOrder', 'OrderController@deleteOrder');
Route::get('/paymentProcess', 'InvoiceController@pending');
Route::get('/paymentSuccess', 'InvoiceController@success');
Route::post('/paymentSuccess', 'InvoiceController@getter');
Route::get('/paymentErr', 'InvoiceController@err');
//Route::get('/orders', 'OrderController@getOrdersByDate');
Route::post('/orders', 'OrderController@getOrdersByMonth');
Route::get('/adminordersbydate', 'OrderController@getAdminOrdersByDate');
Route::get('/about', 'HomeController@about');


Route::get('setting', 'SettingController@index')->name('setting.index');
Route::get('instruments', 'InstrumentController@index')->name('instrument.index');



Route::get('/home', 'HomeController@index');

Route::post('check_datetime', 'OrderController@checkDatetime');

Route::resource('session', 'SessionController');

Route::group([ 'prefix' => 'admin', 'middleware' => 'auth' ], function (){
    Route::get('/', 'AdminController@admin')->middleware('is_admin')->name('admin.index');
    Route::get('/update_orders', 'AdminController@orders')->middleware('is_admin');


    Route::group([ 'prefix' => 'order' ], function (){
        Route::get('/', 'OrderController@index')->name('orders.index');
        Route::get('/{id}', 'OrderController@show')->name('orders.show');
        Route::get('/edit/{id}', 'OrderController@edit')->name('orders.edit');
        Route::put('/update', 'OrderController@update')->name('orders.update');
        Route::get('/delete/{id}', 'OrderController@delete')->name('orders.delete');


    });
    Route::group([ 'prefix' => 'payment' ], function (){
        Route::put('/update', 'InvoiceController@update');
    });



    Route::group(['namespace' => 'Admin'], function (){

        Route::resource('order-time', 'OrderTimeController')->parameters([
            'order-time' => 'id'
        ]);

        Route::resource('order-instrument', 'OrderInstrumentController')->parameters([
            'order-instrument.destroy' => 'id, order_id'
        ]);

        Route::resource('schedules', 'SchedulesController')->parameters([
            'schedules.destroy' => 'id, order_id'
        ]);
    });

    Route::group(['namespace' => 'Admin'], function (){

        /**
         * Main Setting
         */
        Route::get('setting/delete/{id}', 'SettingController@delete')->name('setting.delete');
        Route::resource('setting', 'SettingController');

        /**
         * Category
         */
        Route::resource('category', 'CategoryController');

        /**
         * Hour
         */
        Route::resource('hour', 'HourController');
        Route::get('/hour/{day}/duplicate/{category_id}', 'HourController@duplicate')->name('hour.duplicate');
        Route::post('/hour/copy/{category_id}', 'HourController@copy')->name('hour.copy');

        /**
         * Discount
         */
        Route::resource('discount', 'DiscountController');

        /**
         * Reservation
         */
        Route::resource('reservation', 'ReservationController');

        /**
         * Instrument
         */
        Route::get('instrument/delete/{id}', 'InstrumentController@delete')->name('instrument.delete');
        Route::resource('instrument', 'InstrumentController');

        /**
         * Security
         */
        Route::resource('security', 'SecurityController');

    });


});

app/Discount.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Discount extends Model
{
    protected $fillable = [
        'category_id',
        'name',
        'value',
        'type',
        'min_hour',
        'min_day',
        'min_day',
        'one_day',
        'only_one_day'
    ];

    public function getEnding()
    {
        return $this->type == 'percent' ? '%' : config('app.currencies')[config('app.default_currency')];
    }

    public function getValue()
    {
        return $this->value . ' ' . $this->getEnding();
    }

    public static function calc($category_id, $data)
    {
        $class = new Discount();

        $totals = [
            'main' => 0.00,
            'sale' => 0.00
        ];

        $discounts = $class::where('category_id', $category_id)->orderBy('value', 'desc')->get();

        foreach ($data['schedules'] as $day) {
            /**
             * while on the main price of hour and add to total
             */
            foreach ($day['hours'] as &$time) {

                $h = Hour::where('day', $day['day'])
                    ->where('category_id', $day['category_id'])
                    ->where('hour', $time)
                    ->first();

                // add to main price
                $totals['main'] += $h->price;

                // clone object Hour
                $time = $h;
            }

            /**
             * while on discounts from larger to smaller
             */

            $sales = [];
            foreach ($discounts as $discount) {

                if ($class->validateDiscount($day, $discount)) // if found discount add to total and break
                {
                    $sales[] = $class->validateDiscount($day, $discount);
                }

            }

            if (count($sales)) {
                $totals['sale'] += min($sales);
            }
        }

        return $totals;
    }

    public static function findSale($category_id)
    {
        return self::where('category_id', $category_id)->get()->count();
    }

    private function validateDiscount($day, $discount)
    {
        $error = [];

        $min_hour = count($day['hours']);

        if ($discount->min_hour > $min_hour) {
            $error[] = 'min_hour does not match';
        }

        if ($discount->only_one_day) {
            if ($discount->one_day != $day['date']) {
                $error[] = 'one_day does not match';
            }
        }

        $total = 0.00;
        $sale = 0.00;

        foreach ($day['hours'] as $key => $day) {
            if ($discount->min_hour - 1 >= $key) {
                $sale += $day->price;
            } else {
                $total += $day->price;
            }
        }

        if ($discount->type == 'percent') {
            $sale -= ($sale * $discount->value / 100);
        } else if ($discount->type == 'static') {
            $sale = $discount->value;
        }

        $total += $sale;

        if (count($error)) {
            return false;
        }

        return $total;

    }
}

app/Http/Controllers/Admin/DiscountController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Discount;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DiscountController extends Controller
{

    private $model;

    public function __construct()
    {
        $this->model = new Discount();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(request()->get('category_id')){
            $category_id = request()->get('category_id');
        }else{
            return redirect()->back();
        }

        return view('admin.discount.create', [
            'category_id' => $category_id
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->merge([
            'only_one_day' => isset($request->only_one_day) ? 1 : 0
        ]);

        $this->validate($request, [
            'category_id' => 'required',
            'name' => 'required',
            'value' => 'required',
            'min_hour' => 'required',
            'min_day' => 'required',
            'type' => 'required',
            'only_one_day' => 'integer'
        ]);


        $discount = $this->model::create($request->all());

        if(isset($discount->id)){
            return redirect()->route('category.edit', ['category_id' => $request->category_id]);
        }else{
            return redirect()->back();
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin.discount.edit', [
            'category_id' => $id
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->model::destroy($id);
        return redirect()->back();
    }
}

resources/views/admin/discount/create.blade.php
@extends('adminl_ayout_without_vue')

@section('title')
    Admin.STUDIO
@endsection

@section('content')

    <section class="main">

        <div class="container">


            <div class="col-sm-12">

                <div class="row mt-3">

                    <div class="col-sm-6 mb-4">
                        <a href="{{ route('category.edit', ['id' => $category_id ]) }}" class="btn btn-block btn-secondary">Вернутся к Категории</a>
                    </div>

                </div>

                <form action="{{ route('discount.store', ['id' => $category_id]) }}" class="mt-3" method="post">
                    @csrf
                    <input type="hidden" name="category_id" value="{{ $category_id }}">

                    <div class="row">


                        <div class="col-sm-12 form-group">

                            <label for="sub_name" class="text-white">Название скидки (например -30% за 3 часа)</label>
                            <input name="name" id="name" type="text" class="form-control" value="{{ old('name') }}" required>

                        </div>

                        <div class="col-sm-12 form-group">

                            <label for="sub_name" class="text-white">Тип скидки</label>
                            <select name="type" class="form-control">
                                <option value="static">Статичиская</option>
                                <option value="percent">Процентная</option>
                            </select>

                        </div>

                        <div class="col-sm-12 form-group">

                            <label for="sub_name" class="text-white">Значение</label>
                            <input name="value" id="value" type="number" min="1" class="form-control" value="{{ old('name') }}" required>

                        </div>

                        <div class="col-sm-12 form-group">

                            <div class="row">

                                <div class="col">

                                    <label for="min_hour" class="text-white">Минимальное кол-во часов</label>
                                    <input name="min_hour" id="min_hour" type="number" class="form-control" value="{{ old('name') }}" required>

                                </div>

                                <div class="col">

                                    <label for="min_day" class="text-white">Минимальное кол-во дней</label>
                                    <input name="min_day" id="min_day" type="number" class="form-control" value="{{ old('name') }}" required>

                                </div>

                            </div>

                        </div>
                        
                        
                        <div class="col-sm-12 form-group">

                            <div class="row">
                                <label for="only_one_day" class="col-sm-2 text-white">Только один день</label>
                                <input type="checkbox" name="only_one_day" id="only_one_day" class="form-control col-sm-1">
                                <input type="date" name="one_day" id="one_day" class="form-control col">
                            </div>

                        </div>


                        <div class="col-sm-12">
                            <button type="submit" class="btn btn-block btn-success">Добавить скидку</button>
                        </div>


                    </div>
                </form>

            </div>

        </div>
    </section>

    <style>
        #one_day {
            visibility: hidden;
        }
        #only_one_day:checked + #one_day {
            visibility: visible;
        }
    </style>
@endsection

resources/views/admin/discount/edit.blade.php
@extends('adminl_ayout_without_vue')

@section('title')
    Admin.STUDIO
@endsection

@section('content')

    <section class="main">

        <div class="container">

            <div class="col-sm-12">

                @if(!isset($hours) || !isset($selected_day))
                    <form action="{{ route('hour.edit', ['id' => $day]) }}" class="mt-5" method="get">
                        @csrf
                        @method('POST')
                        <input type="hidden" name="category_id" value="{{ $category_id }}">

                        <div class="row">

                            <div class="col-sm-12 form-group">

                                <label for="sub_name" class="text-white">Кол-во часов в этом дне</label>
                                <input name="hours" id="hours" type="text" class="form-control" value="{{ old('hours') }}" required>

                            </div>


                            <div class="col-sm-12">
                                <button type="submit" class="btn btn-block btn-success">Добавить время</button>
                            </div>


                        </div>
                    </form>
                @elseif(isset($selected_day) && isset($hours))
                    <form action="{{ route('hour.update', ['category_id' => $category_id]) }}" class="mt-5" method="post">
                        @csrf
                        @method('PUT')

                        <div class="row">

                            <div class="col-sm-6 mb-4">
                                <a href="{{ route('category.edit', ['id' => $category_id ]) }}" class="btn btn-block btn-secondary">Вернутся к Категории</a>
                            </div>

                            <div class="col-sm-6 mb-4">
                                <a href="{{ route('hour.edit', ['id' => $selected_day, 'category_id' => $category_id, 'action' => 'add']) }}" class="btn btn-block btn-info">Добавить время</a>
                            </div>

                            <div class="col-sm-12 form-group">
                                <label for="name" class="text-white">День Недели - {{ $days[$selected_day] }}</label>
                                <input type="hidden" name="day" value="{{ $selected_day }}">
                            </div>

                            @foreach($hours as $hour => $value)

                                <div class="col-sm-12 form-group">

                                    <div class="row">
                                        <input type="hidden" name="data[{{$hour}}][category_id]" value="{{ $category_id }}">
                                        <input type="hidden" name="data[{{$hour}}][day]" value="{{ $selected_day }}">


                                        <div class="col-sm-6 col">
                                            <label for="name" class="text-white"> Час</label>
                                            <input type="number" name="data[{{$hour}}][hour]" class="form-control" value="{{ $value['hour'] }}" required>
                                        </div>

                                        <div class="col-sm-5 col">
                                            <label for="name" class="text-white"> Цена за час</label>
                                            <input type="number" name="data[{{$hour}}][price]" class="form-control" value="{{ $value['price'] }}" required>
                                        </div>

                                        <div class="col-sm-1 col d-flex justify-content-end flex-column align-items-start">
                                            @if(!$hour) <label  class="text-white">Удалить</label> @endif
                                            <input type="checkbox" name="delete[{{$hour}}]" class="form-control " value="{{$hour}}">
                                        </div>
                                    </div>

                                </div>

                            @endforeach

                            @if($new_hours)

                                @foreach(range($hour+1, ($new_hours + $hour)) as $new_hour)

                                    <div class="col-sm-12 form-group">

                                        <div class="row">
                                            <input type="hidden" name="data[{{$new_hour}}][category_id]" value="{{ $category_id }}">
                                            <input type="hidden" name="data[{{$new_hour}}][day]" value="{{ $selected_day }}">


                                            <div class="col-sm-6 col">
                                                <label for="name" class="text-white"> Час</label>
                                                <input type="number" name="data[{{$new_hour}}][hour]" class="form-control" required>
                                            </div>

                                            <div class="col-sm-5 col">
                                                <label for="name" class="text-white"> Цена за час</label>
                                                <input type="number" name="data[{{$new_hour}}][price]" class="form-control" required>
                                            </div>

                                            <div class="col-sm-1 col d-flex justify-content-end flex-column align-items-start">
                                                @if(!$hour) <label  class="text-white">Удалить</label> @endif
                                                <input type="checkbox" name="delete[{{$new_hour}}]" class="form-control " value="{{$new_hour}}">
                                            </div>
                                        </div>

                                    </div>

                                @endforeach

                            @endif


                            <div class="col-sm-12">
                                <button type="submit" class="btn btn-block btn-success">Сохранить время</button>
                            </div>


                        </div>
                    </form>
                @endif

            </div>

        </div>
    </section>

@endsection